// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQp0LI1WgrmQl7pLaWH47rY2Zg3qQ_qoQ',
    appId: '1:473490320331:web:bcdcc441e6c706f569a44e',
    messagingSenderId: '473490320331',
    projectId: 'sehatbersama-9c2af',
    authDomain: 'sehatbersama-9c2af.firebaseapp.com',
    storageBucket: 'sehatbersama-9c2af.firebasestorage.app',
    measurementId: 'G-BNNSHRJCPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsmDGx0ZUUVFlfbcPtaurZYxxmwL56gDo',
    appId: '1:473490320331:android:c9152bebe6c2d5cb69a44e',
    messagingSenderId: '473490320331',
    projectId: 'sehatbersama-9c2af',
    storageBucket: 'sehatbersama-9c2af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUAorJd87sjQV5hlVSi8H5HGTuQvyPn7M',
    appId: '1:473490320331:ios:c73d3a06c3220c6f69a44e',
    messagingSenderId: '473490320331',
    projectId: 'sehatbersama-9c2af',
    storageBucket: 'sehatbersama-9c2af.firebasestorage.app',
    iosBundleId: 'com.example.sehatBersama',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUAorJd87sjQV5hlVSi8H5HGTuQvyPn7M',
    appId: '1:473490320331:ios:c73d3a06c3220c6f69a44e',
    messagingSenderId: '473490320331',
    projectId: 'sehatbersama-9c2af',
    storageBucket: 'sehatbersama-9c2af.firebasestorage.app',
    iosBundleId: 'com.example.sehatBersama',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQp0LI1WgrmQl7pLaWH47rY2Zg3qQ_qoQ',
    appId: '1:473490320331:web:5fea67f31bc4134269a44e',
    messagingSenderId: '473490320331',
    projectId: 'sehatbersama-9c2af',
    authDomain: 'sehatbersama-9c2af.firebaseapp.com',
    storageBucket: 'sehatbersama-9c2af.firebasestorage.app',
    measurementId: 'G-LS867FYTG2',
  );

}